<a href="https://colab.research.google.com/github/shiv1122004/ML/blob/main/day29-sklearn-pipelines/predict-without-pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pickle
import numpy as np

In [3]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Import necessary libraries (you'll need these in the new notebook)
import pickle
import os

# Define the path to your models in Google Drive
models_path = '/content/drive/MyDrive/colab_models'

# Check if the directory exists and list its contents
if os.path.exists(models_path):
    print(f"Models found in: {models_path}")
    print(f"Files: {os.listdir(models_path)}")

    # Load your models
    ohe_sex = pickle.load(open(os.path.join(models_path, 'ohe_sex.pkl'), 'rb'))
    ohe_embarked = pickle.load(open(os.path.join(models_path, 'ohe_embarked.pkl'), 'rb'))
    clf = pickle.load(open(os.path.join(models_path, 'clf.pkl'), 'rb'))

    print("Models loaded successfully!")
else:
    print(f"Error: Models directory not found at {models_path}")

Mounted at /content/drive
Models found in: /content/drive/MyDrive/colab_models
Files: ['clf.pkl', 'ohe_embarked.pkl', 'ohe_sex.pkl']
Models loaded successfully!


In [4]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [ ]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [ ]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

In [ ]:
test_input_sex

array([[0., 1.]])

In [ ]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [ ]:
test_input_embarked

array([[0., 0., 1.]])

In [ ]:
test_input_age = test_input[:,2].reshape(1,1)

In [ ]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [ ]:
test_input_transformed.shape

(1, 10)

In [ ]:
clf.predict(test_input_transformed)

array([1], dtype=int64)